// ⚠️ This file is auto-generated by generate-images.js
// Do not edit this file manually.

import React from 'react';
import { Image, type ImageProps } from 'react-native';
import { images, type ImageName } from './index';
type ImageBaseProps =
  | {
      name: ImageName;
      width?: number;
      height?: number;
      color?: string;
      size?: number;
      uri?: string;
    }
  | {
      name?: never;
      width?: number;
      height?: number;
      color?: string;
      size?: number;
      uri?: string;
    };

export const ImageBase: React.FC<
  ImageBaseProps & Omit<ImageProps, 'uri' | 'size' | 'width' | 'height'>
> = ({ name, uri, size, width = 24, height = 24, color, ...rest }) => {
  return (
    <Image
      source={uri ? { uri } : images[name!]}
      style={{ width: size || width, height: size || height, tintColor: color }}
      {...rest}
    />
  );
};

