// ⚠️ This file is auto-generated by generate-images.js
// Do not edit this file manually.

export const images = {
  ic_close_full_screen: require('./ic_close_full_screen.png'),
  ic_full_screen: require('./ic_full_screen.png'),
  ic_pause: require('./ic_pause.png'),
  ic_play: require('./ic_play.png'),
  ic_replay: require('./ic_replay.png'),
  ic_seek_left: require('./ic_seek_left.png'),
  ic_seek_right: require('./ic_seek_right.png'),
  ic_volume_off: require('./ic_volume_off.png'),
  ic_volume_on: require('./ic_volume_on.png')
};

export type ImageName = keyof typeof images;
